version: '3.5'

services:

  # PostgreSQL
  postgres:
    container_name: postgresDB
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ../smartbraindb/
    ports:
      - "5432:5432"

   # Redis DB
  redis:
    container_name: redisDB
    image: redis
    ports:
      - "6379:6379"

  # Backend API
  smartbrainapi:
    container_name: backend
    build: ../smartbrainapi/
    command: npm start
    working_dir: /usr/src/smartbrainapi
    environment:
      POSTGRES_URI: postgres://test:pass@postgres:5432/smart-brain-docker
      JWT_SECRET: JWT_SECRET
      REDIS_URI: redis://redis:6379
      CLARIFAI_API_KEY: CLARIFAI_API_KEY
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
   # volumes:  # add if in dev mode - it is used to avoid rebuilding the container for every change we make to the code
    #  - ../smartbrainapi:/usr/src/smartbrainapi

  # Web
  smartbrainweb:
    container_name: web
    environment:
      API_HOST: localhost
    build: ../smartbrainweb/
    command: npm start
    working_dir: /usr/src/smartbrainweb
    ports:
      - "3001:3001"

  # Enable these to test load balancer.
  # smartbrainweb1:
  #   container_name: web1
  #   environment:
  #     API_HOST: localhost
  #   build: ../smartbrainweb/
  #   command: npm start
  #   working_dir: /usr/src/smartbrainweb
  #   ports:
  #     - 3001

  # smartbrainweb2:
  #   container_name: web2
  #   environment:
  #     API_HOST: localhost
  #   build: ../smartbrainweb/
  #   command: npm start
  #   working_dir: /usr/src/smartbrainweb
  #   ports:
  #     - 3001

  # smartbrainweb3:
  #   container_name: web3
  #   environment:
  #     API_HOST: localhost
  #   build: ../smartbrainweb/
  #   command: npm start
  #   working_dir: /usr/src/smartbrainweb
  #   ports:
  #     - 3001

  # Load Balancer - Enable this along with the above web services to test load balancer
  # loadbalancer:
  #   container_name: loadbalancer
  #   build: ../loadbalancer/
  #   ports:
  #     - 80:80
  #   links:
  #     - smartbrainweb1
  #     - smartbrainweb2
  #     - smartbrainweb3
  #   volumes:
  #     # allows you to run docker commands inside container
  #     - /var/run/docker.sock:/var/run/docker.sock
